# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
import sys
# sys.path.insert(0, os.path.abspath('.'))
import sphinx_rtd_theme
from sphinx.highlighting import lexers
# -- Project information -----------------------------------------------------

project = 'EvolutionaryModelDiscovery'
copyright = '2018, Chathika Gunaratne'
author = 'Chathika Gunaratne'

# The short X.Y version
version = ''
# The full version, including alpha/beta/rc tags
release = '0.0.4'


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['ntemplates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'
#html_theme_path = sphinx_rtd_theme.get_html_theme_path()

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['nstatic']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'EvolutionaryModelDiscoverydoc'


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'EvolutionaryModelDiscovery.tex', 'EvolutionaryModelDiscovery Documentation',
     'Chathika Gunaratne', 'manual'),
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'evolutionarymodeldiscovery', 'EvolutionaryModelDiscovery Documentation',
     [author], 1)
]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'EvolutionaryModelDiscovery', 'EvolutionaryModelDiscovery Documentation',
     author, 'EvolutionaryModelDiscovery', 'One line description of project.',
     'Miscellaneous'),
]


# -- Extension configuration -------------------------------------------------
#####################################################################################################################################
## description: A lexer and style for NetLogo syntax to be used with Pygments
## author: Jan C. Thiele
##         Department Ecoinformatics, Biometrics and Forest Growth
##         University of Goettingen
## contact: <jthiele at gwdg dot de>
## copyright: JC Thiele, 2011
## version: 0.1.2, for NetLogo 4.1.2 (and before ?)
## license: GPL v2

import re

from pygments.lexer import Lexer, DelegatingLexer, RegexLexer, bygroups, \
     include, using, this

from pygments.lexer import RegexLexer
from pygments.token import *

from pygments.style import Style
from pygments.token import Keyword, Name, Comment, String, Error, \
     Number, Operator, Generic, Whitespace



class NetLogoLexer(RegexLexer):
    """
    For `NetLogo <http://ccl.sesp.northwestern.edu/netlogo/>`_ source code.
    """

    name = 'NetLogo'
    aliases = ['NetLogo']
    filenames = ['*.nlogo', '*.nls']
    mimetypes = ['text/x-netlogo']

    flags = re.IGNORECASE # ignore case

    operants = ['\+','\*','\-','\/','\^','\<','\>','\=','\!\=','\<\=','\>\=']
    
    keywords = ['__includes','directed-link-breed','extensions','end','globals','links-own',
                'patches-own','to-report','to','turtles-own','undirected-link-breed']

    constants = ['false','true','black','gray','white','red','orange','brown','yellow','green','lime',
                 'turquoise','cyan','sky','blue','violet','magenta','pink','e','pi','nobody']

    commands = ['__layout-magspring','__set-line-thickness','ask','ask-concurrent','auto-plot-off','auto-plot-on',
                'back','beep','bk','ca','carefully','cd','clear-all','clear-all-plots','clear-drawing','clear-links',
                'clear-output','clear-patches','clear-plot','clear-turtles','cp','create-link-from','create-links-from',
                'create-links-to','create-links-with','create-link-to','create-link-with','create-ordered-turtles',
                'create-temporary-plot-pen','create-turtles','cro','crt','ct','die','diffuse','diffuse4','display',
                'downhill','downhill4','every','export-all-plots','export-interface','export-output','export-plot',
                'export-view','export-world','face','facexy','fd','file-close','file-close-all','file-delete','file-flush',
                'file-open','file-print','file-show','file-type','file-write','follow','follow-me','foreach','forward','hatch',
                'hide-link','hide-turtle','histogram','home','ht','hubnet-broadcast','hubnet-broadcast-clear-output',
                'hubnet-broadcast-message','hubnet-broadcast-view','hubnet-clear-override','hubnet-clear-overrides',
                'hubnet-fetch-message','hubnet-reset','hubnet-reset-perspective','hubnet-send','hubnet-send-clear-output',
                'hubnet-send-follow','hubnet-send-message','hubnet-send-override','hubnet-send-watch',
                'hubnet-set-client-interface','if','ifelse','import-drawing','import-pcolors','import-pcolors-rgb',
                'import-world','inspect','jump','layout-circle','layout-radial','layout-spring','layout-tutte','left','let',
                'loop','lt','move-to','movie-cancel','movie-close','movie-grab-interface','movie-grab-view','movie-set-frame-rate',
                'movie-start','no-display','output-print','output-show','output-type','output-write','pd','pe','pen-down',
                'pen-erase','pen-up','plot','plot-pen-down','plot-pen-reset','plot-pen-up','plotxy','print','pu','random-seed',
                'repeat','report','reset-perspective','reset-ticks','reset-timer','resize-world','ride','ride-me','right','rp','rt',
                'run','set','set-current-directory','set-current-plot','set-current-plot-pen','set-default-shape',
                'set-histogram-num-bars','set-patch-size','set-plot-pen-color','set-plot-pen-interval','set-plot-pen-mode',
                'set-plot-x-range','set-plot-y-range','setxy','show','show-link','show-turtle','sprout','st','stamp','stamp-erase',
                'stop','tick','tick-advance','tie','type','untie','uphill','uphill4','wait','watch','watch-me','while',
                'with-local-randomness','without-interruption','write']

    reporter = ['breed','abs','acos','all\?','and','any\?','approximate-hsb','approximate-rgb','asin','atan','at-points','autoplot\?',
                'base-colors','behaviorspace-run-number','bf','bl','both-ends','butfirst','but-first','butlast','but-last',
                'can-move\?','ceiling','color','cos','count','date-and-time','distance','distancexy','dx','dy','empty\?','end1',
                'end2','error-message','exp','extract-hsb','extract-rgb','file-at-end\?','file-exists\?','file-read',
                'file-read-characters','file-read-line','filter','first','floor','fput','heading','hidden\?','hsb',
                'hubnet-enter-message\?','hubnet-exit-message\?','hubnet-message','hubnet-message-source','hubnet-message-tag',
                'hubnet-message-waiting\?','ifelse-value','in-cone','in-link-from','in-link-neighbor\?','in-link-neighbors',
                'in-radius','int','is-agent\?','is-agentset\?','is-boolean\?','is-directed-link\?','is-link\?','is-link-set\?',
                'is-list\?','is-number\?','is-patch\?','is-patch-set\?','is-string\?','is-turtle\?','is-turtle-set\?',
                'is-undirected-link\?','item','label','label-color','last','length','link','link-heading','link-length',
                'link-neighbor\?','link-neighbors','links','link-set','link-shapes','link-with','list','ln','log','lput','map',
                'max','max-n-of','max-one-of','max-pxcor','max-pycor','mean','median','member\?','min','min-n-of','min-one-of',
                'min-pxcor','min-pycor','mod','modes','mouse-down\?','mouse-inside\?','mouse-xcor','mouse-ycor','movie-status',
                'my-in-links','my-links','my-out-links','myself','neighbors','neighbors4','netlogo-applet\?','netlogo-version',
                'new-seed','n-of','no-links','no-patches','not','no-turtles','n-values','of','one-of','or','other','other-end',
                'out-link-neighbor\?','out-link-neighbors','out-link-to','patch','patch-ahead','patch-at',
                'patch-at-heading-and-distance','patches','patch-here','patch-left-and-ahead','patch-right-and-ahead',
                'patch-set','patch-size','pcolor','pen-mode','pen-size','plabel','plabel-color','plot-name','plot-pen-exists\?',
                'plot-x-max','plot-x-min','plot-y-max','plot-y-min','position','precision','pxcor','pycor','random',
                'random-exponential','random-float','random-gamma','random-normal','random-poisson','random-pxcor',
                'random-pycor','random-xcor','random-ycor','read-from-string','reduce','remainder','remove','remove-duplicates',
                'remove-item','replace-item','reverse','rgb','round','runresult','scale-color','se','self','sentence',
                'shade-of\?','shape','shapes','shuffle','sin','size','sort','sort-by','sqrt','standard-deviation','subject',
                'sublist','substring','subtract-headings','sum','tan','thickness','ticks','tie-mode','timer','towards',
                'towardsxy','turtle','turtles','turtles-at','turtle-set','turtles-here','turtles-on','user-directory',
                'user-file','user-input','user-new-file','user-one-of','user-yes-or-no\?','variance','who','with','with-max',
                'with-min','word','world-height','world-width','wrap-color','xcor','xor','ycor']

    extension_commands = ['gis:APPLY-COVERAGES','gis:SET-SAMPLING-METHOD','gis:PAINT','gis:SET-TRANSFORMATION',
                          'gis:SET-WORLD-ENVELOPE','gis:SET-COVERAGE-MINIMUM-THRESHOLD','gis:APPLY-RASTER',
                          'gis:SET-COORDINATE-SYSTEM','gis:APPLY-COVERAGE','gis:FILL','gis:MYWORLD-SEND-DATASET',
                          'gis:SET-TRANSFORMATION-DS','gis:SET-RASTER-VALUE','gis:SET-DRAWING-COLOR','gis:IMPORT-WMS-DRAWING',
                          'gis:LOAD-COORDINATE-SYSTEM','gis:SET-COVERAGE-MAXIMUM-THRESHOLD','gis:SET-WORLD-ENVELOPE-DS',
                          'gis:STORE-DATASET','gis:DRAW','gogo:OPEN','gogo:SET-BURST-MODE','gogo:OUTPUT-PORT-THISWAY',
                          'gogo:TALK-TO-OUTPUT-PORTS','gogo:OUTPUT-PORT-ON','gogo:CLOSE','gogo:OUTPUT-PORT-OFF',
                          'gogo:SET-OUTPUT-PORT-POWER','gogo:STOP-BURST-MODE','gogo:OUTPUT-PORT-REVERSE','gogo:OUTPUT-PORT-THATWAY',
                          'gogo:OUTPUT-PORT-COAST','sound:PLAY-SOUND-LATER','sound:START-NOTE','sound:STOP-SOUND','sound:STOP-MUSIC',
                          'sound:PLAY-NOTE','sound:STOP-INSTRUMENT','sound:PLAY-NOTE-LATER','sound:PLAY-SOUND','sound:STOP-NOTE',
                          'sound:PLAY-SOUND-AND-WAIT','sound:LOOP-SOUND','sound:PLAY-DRUM','profiler:START',
                          'profiler:STOP','profiler:RESET','bitmap:COPY-TO-PCOLORS','bitmap:COPY-TO-DRAWING',
                          'bitmap:EXPORT','qtj:camera-start','qtj:camera-stop','qtj:camera-select','qtj:movie-open','qtj:movie-start',
                          'qtj:movie-stop','qtj:movie-open-player','qtj:movie-close','qtj:movie-image','qtj:movie-set-time',
                          'table:REMOVE','table:PUT','table:CLEAR','array:SET','r:STOPDEBUG','r:STARTJRIDEBUG','r:EVAL',
                          'r:INTERACTIVESHELL','r:PUTLIST','r:STOPJRIDEBUG','r:PUTAGENT','r:STARTDEBUG','r:PUTNAMEDLIST',
                          'r:PUTDATAFRAME','r:PUTAGENTDF','r:MESSAGEWINDOW','r:PUT','r:CLEAR','multiview:close','multiview:rename',
                          'multiview:repaint']


    extension_reporter = ['gis:RASTER-SAMPLE','gis:RASTER-WORLD-ENVELOPE','gis:COVERAGE-MINIMUM-THRESHOLD','gis:PROPERTY-MAXIMUM',
                          'gis:LOAD-DATASET','gis:INTERSECTS\?','gis:MYWORLD-GET-DATASET','gis:CONTAINED-BY\?','gis:HEIGHT-OF',
                          'gis:FIND-ONE-FEATURE','gis:LOCATION-OF','gis:LINK-DATASET','gis:PROPERTY-VALUE','gis:FIND-RANGE',
                          'gis:CONTAINS\?','gis:PATCH-DATASET','gis:FIND-LESS-THAN','gis:RESAMPLE','gis:TYPE-OF','gis:ENVELOPE-UNION-OF',
                          'gis:COVERAGE-MAXIMUM-THRESHOLD','gis:VERTEX-LISTS-OF','gis:WIDTH-OF','gis:DRAWING-COLOR','gis:CREATE-RASTER',
                          'gis:PROPERTY-MINIMUM','gis:RELATIONSHIP-OF','gis:INTERSECTING','gis:MINIMUM-OF','gis:MYWORLD-LAYERS',
                          'gis:WORLD-ENVELOPE','gis:ENVELOPE-OF','gis:HAVE-RELATIONSHIP\?','gis:MAXIMUM-OF','gis:TURTLE-DATASET',
                          'gis:PROPERTY-NAMES','gis:FIND-GREATER-THAN','gis:CONVOLVE','gis:CENTROID-OF','gis:SHAPE-TYPE-OF',
                          'gis:FEATURE-LIST-OF','gis:SAMPLING-METHOD-OF','gis:FIND-FEATURES','gis:RASTER-VALUE','gogo:SENSOR',
                          'gogo:BURST-VALUE','gogo:PING','gogo:PORTS','gogo:OPEN\?','sound:__SYNTH-DUMP','sound:DRUMS',
                          'sound:INSTRUMENTS','profiler:REPORT','profiler:INCLUSIVE-TIME','profiler:CALLS','profiler:EXCLUSIVE-TIME',
                          'bitmap:CHANNEL','bitmap:AVERAGE-COLOR','bitmap:IMPORT','bitmap:TO-GRAYSCALE','bitmap:HEIGHT',
                          'bitmap:DIFFERENCE-RGB','bitmap:FROM-VIEW','bitmap:SCALED','bitmap:WIDTH','qtj:camera-image',
                          'table:MAKE','table:FROM-LIST','table:TO-LIST','table:GET','table:HAS-KEY\?','table:KEYS','table:LENGTH',
                          'array:TO-LIST','array:FROM-LIST','array:ITEM','array:LENGTH','r:GET','multiview:newView']

    tokens = {
        'root': [
            (r';.*\n', Comment.Single), # line comment
            (r'["].*?["]', String), # strings "..."
            (r'(?<=\s)[+*/<>=!#%^&|`?^-]+(?=\s)', Operator), # operators
            #(r'(?<=\s)(breed)(\s*)(\[)(\s*)(?<=[\s\(\[])[.\S]+?(?=[\s\)\]])(\s+)(?<=[\s\(\[])[.\S]+?(?=[\s\)\]])(\])', Keyword), # usage of breed as keyword
            # this pattern is a reconstruction of the (more or less) bug in NetLogo, indicating breed as if it is in front of a new line 
            (r'(?<=\n)(breed)(\s*)(\[)(\s*)([.\S]+)(\s+)([.\S]+)(\s*)(\])', bygroups(Keyword,Whitespace,Name.Namespace,Whitespace,Name,Whitespace,Name,Whitespace,Name.Namespace)), # usage of breed as keyword
            (r'(%s)(?=[\s\]\)])' % '|'.join(keywords), Keyword), # keywords
            (r'(?<=[\s\[\(])(%s)(?=[\s\]\)])' % '|'.join(commands), Name.Tag), # commands
            (r'(?<=[\s\[\(])(%s)(?=[\s\]\)])' % '|'.join(reporter), Name.Function), # reporter
            (r'(?<=[\s\[\(])(%s)(?=[\s\]\)])' % '|'.join(constants), Name.Constant), # constants
            (r'(?<=[\s\[\(])(%s)(?=[\s\]\)])' % '|'.join(extension_commands), Name.Tag), # command (extensions)
            (r'(?<=[\s\[\(])(%s)(?=[\s\]\)])' % '|'.join(extension_reporter), Name.Function), # reporter (extensions)
            (r'(?<=[\s\[\(])[0-9][0-9]*\.[0-9]+([eE][0-9]+)?[fd]?(?=[\s\]\)])', Number.Float), # float
            (r'(?<=[\s\[\(])[0-9]+L?(?=[\s\]\)])', Number.Integer), # integer
            (r'\s+', Whitespace), # whitespace
            (r'[\(\)\[\]]', Name.Namespace), # brace
            (r'(?<=[\s\(\[])[.\S]+?(?=[\s\)\]])', Name) # variable and procedure names
        ],
    }

    def get_tokens_unprocessed(self, text):
        # cut at the beginning of the interface and information tab stuff
        substrings = text.partition('@#$#@#$#@')
        text = substrings[0]
        stack = ['root']
        for item in RegexLexer.get_tokens_unprocessed(self, text, stack):
            yield item


class NetLogoStyle(Style):
    """
    A NetLogo style, according to the NetLogo Editor Highlighting.
    """

    default_style = ""

    styles = {
        Whitespace:                "#ffffff",

        Comment:                   "#5a5a5a",

        Operator:                  "#660096",

        Keyword:                   "#007f69",

        Name:                      "#090909",
        Name.Function:             "#660096",
        Name.Namespace:            "#090909",
        Name.Constant:             "#963700",        
        Name.Tag:                  "#0000aa",

        Number:                    "#963700",

        String:                    "#963700",

        #Error:                     "#F00 bg:#FAA"
    }
#####################################################################################################################################
lexers['netlogo'] = NetLogoLexer()
